package com.mostafa.fci.recyclerviewdemo

data class Word(var arabicText:String , var englishText: String)

object Supplier{
    val words = listOf<Word> (  Word("واحد","one")
            ,Word("واحد","one")
            ,Word("واحد","two")
            ,Word("واحد","three")
            ,Word("واحد","four")
            ,Word("واحد","five")
            ,Word("واحد","six")
            ,Word("واحد","seven")
            ,Word("واحد","eight")
            ,Word("واحد","nine")
            ,Word("واحد","ten")
            ,Word("واحد","one")
            ,Word("واحد","two")
            ,Word("واحد","three")
            ,Word("واحد","four")
            ,Word("واحد","five")
            ,Word("واحد","six")
            ,Word("واحد","seven")
            ,Word("واحد","eight")
            ,Word("واحد","nine")
            ,Word("واحد","ten")
            ,Word("واحد","one")
            ,Word("واحد","two")
            ,Word("واحد","three")
            ,Word("واحد","four")
            ,Word("واحد","five")
            ,Word("واحد","six")
            ,Word("واحد","seven")
            ,Word("واحد","eight")
            ,Word("واحد","nine")
            ,Word("واحد","ten")
    )
}